# id, name, code, home league, country, p, onp, al, ad, city, tz
EXTRA=[
# Top 14
('toulouse','Stade Toulousain','TLS','T14','France','#C8102E','#111111','#C8102E','#FF7A83','Toulouse','Europe/Paris'),
('larochelle','Stade Rochelais','LAR','T14','France','#F2C200','#111111','#8A6D00','#F2C200','La Rochelle','Europe/Paris'),
('bordeaux','Union Bordeaux Bègles','UBB','T14','France','#5A1E3C','#FFFFFF','#8A2E5C','#E590BC','Bordeaux','Europe/Paris'),
('racing92','Racing 92','R92','T14','France','#8CC8F0','#0B1E3F','#1F6FB2','#8CC8F0','Paris','Europe/Paris'),
('stadefrancais','Stade Français','SFP','T14','France','#E4007C','#0B1E3F','#C4006B','#FF7ABF','Paris','Europe/Paris'),
('toulon','RC Toulon','RCT','T14','France','#C8102E','#111111','#C8102E','#FF7A83','Toulon','Europe/Paris'),
('clermont','ASM Clermont Auvergne','ASM','T14','France','#F7D117','#0B2A6B','#0B2A6B','#F7D117','Clermont-Ferrand','Europe/Paris'),
('montpellier','Montpellier Hérault Rugby','MHR','T14','France','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Montpellier','Europe/Paris'),
('castres','Castres Olympique','CO','T14','France','#1B3F95','#FFFFFF','#1B3F95','#8AA8F0','Castres','Europe/Paris'),
('pau','Section Paloise','PAU','T14','France','#0E7A3E','#FFFFFF','#0E7A3E','#62D696','Pau','Europe/Paris'),
('bayonne','Aviron Bayonnais','AB','T14','France','#6EB8E6','#0B1E3F','#1C6FB0','#8CC8F0','Bayonne','Europe/Paris'),
('lyon','Lyon OU','LOU','T14','France','#C8102E','#FFFFFF','#1B3F95','#8AA8F0','Lyon','Europe/Paris'),
('perpignan','USA Perpignan','USAP','T14','France','#E2001A','#F2C200','#C8102E','#F2C200','Perpignan','Europe/Paris'),
('brive','CA Brive','CAB','T14','France','#111111','#FFFFFF','#555B63','#C9CED4','Brive','Europe/Paris'),
('oyonnax','Oyonnax Rugby','OYO','T14','France','#C8102E','#FFFFFF','#C8102E','#FF7A83','Oyonnax','Europe/Paris'),
('vannes','Rugby Club Vannes','RCV','T14','France','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Vannes','Europe/Paris'),
('montauban','US Montauban','USM','T14','France','#1B3F95','#FFFFFF','#1B3F95','#8AA8F0','Montauban','Europe/Paris'),
('biarritz','Biarritz Olympique','BO','T14','France','#C8102E','#FFFFFF','#C8102E','#FF7A83','Biarritz','Europe/Paris'),
('grenoble','FC Grenoble','FCG','T14','France','#C8102E','#1B3F95','#1B3F95','#8AA8F0','Grenoble','Europe/Paris'),
('provence','Provence Rugby','PR','T14','France','#0B2A6B','#F2C200','#1D4FB0','#F2C200','Aix-en-Provence','Europe/Paris'),
('montois','Stade Montois','SM','T14','France','#F2C200','#111111','#8A6D00','#F2C200','Mont-de-Marsan','Europe/Paris'),
# Super Rugby
('crusaders','Crusaders','CRU','SR','New Zealand','#C8102E','#111111','#C8102E','#FF7A83','Christchurch','Pacific/Auckland'),
('blues','Blues','BLU','SR','New Zealand','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Auckland','Pacific/Auckland'),
('chiefs','Chiefs','CHI','SR','New Zealand','#111111','#F2C200','#B3121B','#F2C200','Hamilton','Pacific/Auckland'),
('hurricanes','Hurricanes','HUR','SR','New Zealand','#F2C200','#111111','#8A6D00','#F2C200','Wellington','Pacific/Auckland'),
('highlanders','Highlanders','HIG','SR','New Zealand','#0B2A6B','#F2C200','#1D4FB0','#F2C200','Dunedin','Pacific/Auckland'),
('brumbies','Brumbies','BRU','SR','Australia','#0B2A6B','#F2C200','#1D4FB0','#F2C200','Canberra','Australia/Sydney'),
('reds','Queensland Reds','RED','SR','Australia','#8A1538','#FFFFFF','#8A1538','#F07FA0','Brisbane','Australia/Brisbane'),
('waratahs','NSW Waratahs','WAR','SR','Australia','#6EB8E6','#0B1E3F','#1C6FB0','#8CC8F0','Sydney','Australia/Sydney'),
('force','Western Force','FOR','SR','Australia','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Perth','Australia/Perth'),
('rebels','Melbourne Rebels','REB','SR','Australia','#0B1E3F','#FFFFFF','#C8102E','#FF7A83','Melbourne','Australia/Melbourne'),
('drua','Fijian Drua','DRU','SR','Fiji','#0B6FB0','#FFFFFF','#0B6FB0','#8CC8F0','Suva','Pacific/Fiji'),
('moana','Moana Pasifika','MOA','SR','Samoa','#0B6B8A','#FFFFFF','#0B6B8A','#6FD3F0','Auckland','Pacific/Auckland'),
# Currie Cup
('cheetahs','Cheetahs','CHE','CC','South Africa','#F28C00','#111111','#B35F00','#F2A640','Bloemfontein','Africa/Johannesburg'),
('griquas','Griquas','GRI','CC','South Africa','#6EB8E6','#0B1E3F','#1C6FB0','#8CC8F0','Kimberley','Africa/Johannesburg'),
('pumas','Pumas','PUM','CC','South Africa','#0E7A3E','#FFFFFF','#0E7A3E','#62D696','Mbombela','Africa/Johannesburg'),
('griffons','Griffons','GRF','CC','South Africa','#7A2A8A','#FFFFFF','#7A2A8A','#D69AE6','Welkom','Africa/Johannesburg'),
('boland','Boland Cavaliers','BOL','CC','South Africa','#0E7A3E','#FFFFFF','#0E7A3E','#62D696','Wellington','Africa/Johannesburg'),
# NPC
('auckland','Auckland','AKL','NPC','New Zealand','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Auckland','Pacific/Auckland'),
('bop','Bay of Plenty','BOP','NPC','New Zealand','#0B2A6B','#F2C200','#1D4FB0','#F2C200','Tauranga','Pacific/Auckland'),
('canterbury','Canterbury','CAN','NPC','New Zealand','#C8102E','#111111','#C8102E','#FF7A83','Christchurch','Pacific/Auckland'),
('counties','Counties Manukau','CMA','NPC','New Zealand','#C8102E','#FFFFFF','#0E7A3E','#62D696','Pukekohe','Pacific/Auckland'),
('hawkesbay','Hawke\'s Bay','HB','NPC','New Zealand','#111111','#FFFFFF','#8C1D40','#E07AA0','Napier','Pacific/Auckland'),
('manawatu','Manawatū','MAN','NPC','New Zealand','#0E7A3E','#FFFFFF','#0E7A3E','#62D696','Palmerston North','Pacific/Auckland'),
('northharbour','North Harbour','NH','NPC','New Zealand','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Albany','Pacific/Auckland'),
('northland','Northland','NLD','NPC','New Zealand','#6EB8E6','#0B1E3F','#1C6FB0','#8CC8F0','Whangārei','Pacific/Auckland'),
('otago','Otago','OTA','NPC','New Zealand','#0B2A6B','#F2C200','#1D4FB0','#F2C200','Dunedin','Pacific/Auckland'),
('southland','Southland','STL','NPC','New Zealand','#8C1D40','#F2C200','#8C1D40','#F2C200','Invercargill','Pacific/Auckland'),
('taranaki','Taranaki','TAR','NPC','New Zealand','#F2C200','#111111','#8A6D00','#F2C200','New Plymouth','Pacific/Auckland'),
('tasman','Tasman','TAS','NPC','New Zealand','#E35205','#0B2A6B','#B34204','#F59A5F','Nelson','Pacific/Auckland'),
('waikato','Waikato','WAI','NPC','New Zealand','#C8102E','#F2C200','#C8102E','#F2C200','Hamilton','Pacific/Auckland'),
('wellington','Wellington','WEL','NPC','New Zealand','#111111','#F2C200','#8A6D00','#F2C200','Wellington','Pacific/Auckland'),
# Japan League One
('wildknights','Saitama Wild Knights','SWK','JL1','Japan','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Kumagaya','Asia/Tokyo'),
('spears','Kubota Spears','KSP','JL1','Japan','#E35205','#FFFFFF','#B34204','#F59A5F','Funabashi','Asia/Tokyo'),
('sungoliath','Tokyo Sungoliath','TSG','JL1','Japan','#F2C200','#111111','#8A6D00','#F2C200','Tokyo','Asia/Tokyo'),
('bravelupus','Toshiba Brave Lupus','BLT','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Fuchu','Asia/Tokyo'),
('steelers','Kobe Steelers','KS','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Kobe','Asia/Tokyo'),
('verblitz','Toyota Verblitz','TV','JL1','Japan','#C8102E','#111111','#C8102E','#FF7A83','Toyota','Asia/Tokyo'),
('bluerevs','Shizuoka Blue Revs','SBR','JL1','Japan','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Iwata','Asia/Tokyo'),
('eagles','Yokohama Canon Eagles','YCE','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Yokohama','Asia/Tokyo'),
('blackrams','Black Rams Tokyo','BRT','JL1','Japan','#111111','#FFFFFF','#555B63','#C9CED4','Tokyo','Asia/Tokyo'),
('dynaboars','Sagamihara DynaBoars','SDB','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Sagamihara','Asia/Tokyo'),
('heat','Mie Honda Heat','MHH','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Suzuka','Asia/Tokyo'),
('drocks','Urayasu D-Rocks','UDR','JL1','Japan','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Urayasu','Asia/Tokyo'),
('liners','Hanazono Kintetsu Liners','HKL','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Osaka','Asia/Tokyo'),
('greenrockets','Green Rockets Tokatsu','GRT','JL1','Japan','#0E7A3E','#FFFFFF','#0E7A3E','#62D696','Kashiwa','Asia/Tokyo'),
('shuttles','Toyota Industries Shuttles Aichi','SA','JL1','Japan','#0B2A6B','#FFFFFF','#1D4FB0','#8AB0F5','Kariya','Asia/Tokyo'),
('bluesharks','Shimizu Koto Blue Sharks','KBS','JL1','Japan','#0B6FB0','#FFFFFF','#0B6FB0','#8CC8F0','Tokyo','Asia/Tokyo'),
# European cup-only
('redhurricanes','Red Hurricanes Osaka','RHO','JL1','Japan','#C8102E','#FFFFFF','#C8102E','#FF7A83','Osaka','Asia/Tokyo'),
('blacklion','Black Lion','BLK','EPC','Georgia','#111111','#FFFFFF','#C8102E','#FF7A83','Tbilisi','Asia/Tbilisi'),
]
ALIAS={'Stade Toulousain':'toulouse','Stade Rochelais':'larochelle','Union Bordeaux Bègles':'bordeaux','Racing 92':'racing92','Stade Français':'stadefrancais','Stade Français Paris':'stadefrancais','RC Toulon':'toulon','RC Toulonnais':'toulon','ASM Clermont Auvergne':'clermont','Montpellier Hérault Rugby':'montpellier','Castres Olympique':'castres','Section Paloise':'pau','Aviron Bayonnais':'bayonne','Lyon OU':'lyon','Lyon OU Rugby':'lyon','USA Perpignan':'perpignan','CA Brive':'brive','Oyonnax Rugby':'oyonnax','Rugby Club Vannes':'vannes','US Montauban':'montauban','Biarritz Olympique':'biarritz','FC Grenoble':'grenoble','Provence Rugby':'provence','Stade Montois':'montois',
'Crusaders (rugby union)':'crusaders','Blues (Super Rugby)':'blues','Chiefs (Super Rugby)':'chiefs','Hurricanes (rugby union)':'hurricanes','Highlanders (rugby union)':'highlanders','ACT Brumbies':'brumbies','Queensland Reds':'reds','New South Wales Waratahs':'waratahs','Western Force':'force','Melbourne Rebels':'rebels','Fijian Drua':'drua','Moana Pasifika':'moana',
'Cheetahs (rugby union)':'cheetahs','Free State Cheetahs':'cheetahs','Griquas (rugby union)':'griquas','Pumas (Currie Cup)':'pumas','Griffons (rugby union)':'griffons','Boland Cavaliers':'boland','Blue Bulls':'bulls','Bulls (rugby)':'bulls','Golden Lions':'lions','Sharks (Currie Cup)':'sharks',
'Saitama Wild Knights':'wildknights','Kubota Spears':'spears','Kubota Spears Funabashi Tokyo Bay':'spears','Tokyo Sungoliath':'sungoliath','Toshiba Brave Lupus Tokyo':'bravelupus','Kobelco Kobe Steelers':'steelers','Toyota Verblitz':'verblitz','Shizuoka Blue Revs':'bluerevs','Yokohama Canon Eagles':'eagles','Black Rams Tokyo':'blackrams','Mitsubishi Sagamihara DynaBoars':'dynaboars','Mie Honda Heat':'heat','Urayasu D-Rocks':'drocks','Hanazono Kintetsu Liners':'liners','Green Rockets Tokatsu':'greenrockets','Toyota Industries Shuttles Aichi':'shuttles','Toyota Industries Corporation Shuttles Aichi':'shuttles','Shimizu Koto Blue Sharks':'bluesharks',
'Black Lion (rugby union)':'blacklion','Shining Arcs Tokyo-Bay Urayasu':'drocks','NTT Communications Shining Arcs':'drocks','NTT DoCoMo Red Hurricanes Osaka':'redhurricanes','Tochigi Honda Heat':'heat','Toshiba Brave Lupus Musashi':'bravelupus',
'#RUT:Bordeaux Bègles':'bordeaux','#RUT:Castres':'castres','#RUT:Pau':'pau','#RUT:Lyon':'lyon','#RUT:La Rochelle':'larochelle','#RUT:Stade Français':'stadefrancais','#RUT:Bayonne':'bayonne','#RUT:Toulon':'toulon','#RUT:Perpignan':'perpignan','#RUT:Toulouse':'toulouse','#RUT:Clermont':'clermont','#RUT:Montpellier':'montpellier','#RUT:Vannes':'vannes','#RUT:Racing 92':'racing92','#RUT:Montauban':'montauban'}
for k in ['Auckland','Bay of Plenty','Canterbury','Counties Manukau',"Hawke's Bay",'Manawatu','North Harbour','Northland','Otago','Southland','Taranaki','Tasman','Waikato','Wellington']:
    ALIAS[k+' (National Provincial Championship)']={'Bay of Plenty':'bop','Counties Manukau':'counties',"Hawke's Bay":'hawkesbay','North Harbour':'northharbour','Manawatu':'manawatu'}.get(k,k.lower())
